name: franka_banana_rgb

task_name: franka_banana_rgb_50

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    img:
      shape: [3, 84, 84]
      type: img
      horizon: 2
    agent_pos:
      shape: [7]
      type: low_dimx
      horizon: 2
  action:
    shape: [7]
    horizon: 16

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.lab_real_dataset.LabRealDataset
  zarr_path: data_sirius/cole_banana_redo.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.0
  max_train_episodes: 90
  has_images: True
  has_pointclouds: False
