name: franka_sirius_banana

task_name: franka_sirius_banana

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [4096, 6]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dimx
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.lab_real_dataset.LabRealDataset
  zarr_path: data_sirius/combined_banana.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.0
  max_train_episodes: 90
  weighted: True
